import { v4 as uuid } from "uuid";

/**
 * Product Database can be added here.
 * You can add products of your wish with different attributes
 * */

export const products = [
  {
    _id: uuid(),
    title: " Men Round Neck Black T-Shirt",
    rating:"4",
    price: "5199",
    size:"medium",
    img:"	https://rukminim2.flixcart.com/image/714/857/kfbfr…rithik-roshan-original-imafvswfsfanbqye.jpeg?q=50",
    categoryName: "men-clothing",
  },
  {
    _id: uuid(),
    title: " Men Round Neck Green T-Shirt",
    rating:"4.3",
    price: "789",
    size:"medium",
    img:"	https://rukminim2.flixcart.com/image/714/857/kfbfr…rithik-roshan-original-imafvswfsfanbqye.jpeg?q=50",
    categoryName: "men-clothing",
  },
  {
    _id: uuid(),
    title: "Men Regular Fit Solid Spread Collar Casual Shirt",
    rating:"4.3",
    price: "1200",
    size:"small",
    img:"	https://rukminim2.flixcart.com/image/714/857/kfbfr…rithik-roshan-original-imafvswfsfanbqye.jpeg?q=50",
    categoryName: "men-clothing",
  },
  {
    _id: uuid(),
    title: "Shoes For Men  (Brown)",
    rating:"3.5",
    price: "2000",
    size:"medium",
    img:"	https://rukminim2.flixcart.com/image/714/857/kfbfr…rithik-roshan-original-imafvswfsfanbqye.jpeg?q=50",
    categoryName: "footwear",
  },
  {
    _id: uuid(),
    title: "Men Multicolor Sports Sandal",
    rating:"3",
    price: "3100",
    size:"medium",
    img:"	https://rukminim2.flixcart.com/image/714/857/kfbfr…rithik-roshan-original-imafvswfsfanbqye.jpeg?q=50",
    categoryName: "footwear",
  },
  {
    _id: uuid(),
    title: "Men Tan Sandal ",
    rating:"2.3",
    price: "1220",
    size:"small",
    img:"	https://rukminim2.flixcart.com/image/714/857/kfbfr…rithik-roshan-original-imafvswfsfanbqye.jpeg?q=50",
    categoryName: "footwear",
  },
  {
    _id: uuid(),
    title: "INDI EXCLUSIVE Sneaker For Men  (Navy) ",
    rating:"2.3",
    price: "1220",
    size:"medium",
    img:"	https://rukminim2.flixcart.com/image/714/857/kfbfr…rithik-roshan-original-imafvswfsfanbqye.jpeg?q=50",
    categoryName: "footwear",
  },
  {
    _id: uuid(),
    title: " Slip On For Men  (Black) ",
    rating:"4.3",
    price: "5000",
    size:"medium",
    img:"	https://rukminim2.flixcart.com/image/714/857/kfbfr…rithik-roshan-original-imafvswfsfanbqye.jpeg?q=50",
    categoryName: "footwear",
  },
  {
    _id: uuid(),
    title: "Puma Backpack",
    rating:"3.5",
    price: "4100",
    size:"medium",
    img:"	https://rukminim2.flixcart.com/image/714/857/kfbfr…rithik-roshan-original-imafvswfsfanbqye.jpeg?q=50",
    categoryName: "men-clothing",
  },
  {
    _id: uuid(),
    title: "HP Core i3 11th Gen",
    rating:"4",
    price: "41000",
    img:"	https://rukminim2.flixcart.com/image/714/857/kfbfr…rithik-roshan-original-imafvswfsfanbqye.jpeg?q=50",
    categoryName: "electronics",
  },
  {
    _id: uuid(),
    title: "DELL Inspiron Core i3 11th Gen",
    rating:"4",
    price: "50000",
    img:"	https://rukminim2.flixcart.com/image/714/857/kfbfr…rithik-roshan-original-imafvswfsfanbqye.jpeg?q=50",
    categoryName: "electronics",
  },
  {
    _id: uuid(),
    title: "realme Book (Slim) Core i3 11th Gen ",
    rating:"4.5",
    price: "50000", 
    img:"	https://rukminim2.flixcart.com/image/714/857/kfbfr…rithik-roshan-original-imafvswfsfanbqye.jpeg?q=50",
    categoryName: "electronics",
  },
  {
    _id: uuid(),
    title: "lenovo-ideapad-3-ryzen-5",
    rating:"4.3",
    price: "43000",
    img:"	https://rukminim2.flixcart.com/image/714/857/kfbfr…rithik-roshan-original-imafvswfsfanbqye.jpeg?q=50",
    categoryName: "electronics",
  },
  {
    _id: uuid(),
    title: "HP Ryzen 5 Hexa Core 5500U ",
    rating:"4",
    price: "50000",
    img:"	https://rukminim2.flixcart.com/image/714/857/kfbfr…rithik-roshan-original-imafvswfsfanbqye.jpeg?q=50",
    categoryName: "men-clothing",
  },
  {
    _id: uuid(),
    title: "APPLE 2020 Macbook Air M1",
    rating:"5",
    price: "77000",
    img:"	https://rukminim2.flixcart.com/image/714/857/kfbfr…rithik-roshan-original-imafvswfsfanbqye.jpeg?q=50",
    categoryName: "electronics",
  },
  {
    _id: uuid(),
    title: "Nokia PureBook X14 Core i5 10th Gen ",
    rating:"4.3",
    price: "50000",
    img:"	https://rukminim2.flixcart.com/image/714/857/kfbfr…rithik-roshan-original-imafvswfsfanbqye.jpeg?q=50",
    categoryName: "electronics",
  },
  {
    _id: uuid(),
    title: "Nokia PureBook X14 Core i5 10th Gen ",
    rating:"4.3",
    price: "75000",
    img:"	https://rukminim2.flixcart.com/image/714/857/kfbfr…rithik-roshan-original-imafvswfsfanbqye.jpeg?q=50",
    categoryName: "electronics",
  },
];
